version: '3'
services:
  apache:
    build: .docker/apache
    container_name: marketplace_apache
    ports:
      - 8080:80
    volumes:
      - .docker/config/vhosts:/etc/apache2/sites-enabled
      - .:/home/wwwroot/marketplace
    depends_on:
      - php

  php:
    build: .docker/php
    container_name: marketplace_php
    volumes:
      - .:/home/wwwroot/marketplace